apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort  # Change to LoadBalancer if using a cloud provider
  ports:
  - port: 4200           # Port exposed by the service
    targetPort: 4200   # Port on the container
    nodePort: 30003   # Node port
  selector:
    app: frontend
